# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0dd8b7a8251dada9e5437709dabc1ad896a151e7aac7a6f0978d88db9a5935527b7d8adb0eea883e61e90d196f3d4a0b819570b311fcb28d75c38d252a4273d8

test:
  secret_key_base: eb61e9dded08616585d779f26ae75489db3454d8aa39424e418fddbb7164e650eed7002d7ed35186be10032c028ac1779a1a8674c78a95bcdb34f92224125a0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
